### ISSUE TITLE
Fails to built with default setting on ubuntu 14.04

### ISSUE THREAD

**Issue by cornelinux** [Nitrokey/libnitrokey#11]
I can not compile the library with a normal "make" run.

<pre>
cornelius@puckel ~/src/libnitrokey-fork (git)-[toplevel] % make
clang++-3.6 -c command_id.cc -o build/command_id.o -Iinclude/ -std=c++14 -fPIC 
clang++-3.6 -c device.cc -o build/device.o -Iinclude/ -std=c++14 -fPIC 
In file included from device.cc:2:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/thread:39:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/functional:55:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/tuple:39:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/array:38:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/stdexcept:39:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/string:52:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/basic_string.h:2815:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/ext/string_conversions.h:43:
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/cstdio:120:11: error: no member named 'gets' in the global namespace
  using ::gets;
        ~~^
In file included from device.cc:6:
include/device.h:43:3: warning: declaration does not declare anything [-Wmissing-declarations]
  const;
  ^~~~~
include/device.h:45:3: warning: declaration does not declare anything [-Wmissing-declarations]
  const;
  ^~~~~
2 warnings and 1 error generated.
make: *** [build/device.o] Fehler 1
</pre>

I need to specify additional parameters to get the library built:

<pre>
cornelius@puckel ~/src/libnitrokey-fork (git)-[toplevel] % make CXXFLAGS="-std=c++14 -fPIC -stdlib=libc++" all 
clang++-3.6 -c device.cc -o build/device.o -Iinclude/ -std=c++14 -fPIC -stdlib=libc++
In file included from device.cc:6:
include/device.h:43:3: warning: declaration does not declare anything [-Wmissing-declarations]
  const;
  ^~~~~
include/device.h:45:3: warning: declaration does not declare anything [-Wmissing-declarations]
  const;
  ^~~~~
2 warnings generated.
clang++-3.6 -c log.cc -o build/log.o -Iinclude/ -std=c++14 -fPIC -stdlib=libc++
clang++-3.6 -c misc.cc -o build/misc.o -Iinclude/ -std=c++14 -fPIC -stdlib=libc++
misc.cc:15:40: warning: format specifies type 'unsigned int' but the argument has type 'long' [-Wformat]
    snprintf(formatbuf, 128, "%04x\t", p - pstart);
                              ~~~~     ^~~~~~~~~~
                              %04lx
1 warning generated.
clang++-3.6 -c toplevel.cc -o build/toplevel.o -Iinclude/ -std=c++14 -fPIC -stdlib=libc++
In file included from toplevel.cc:3:
In file included from include/device_proto.h:12:
include/device.h:43:3: warning: declaration does not declare anything [-Wmissing-declarations]
  const;
  ^~~~~
include/device.h:45:3: warning: declaration does not declare anything [-Wmissing-declarations]
  const;
  ^~~~~
In file included from toplevel.cc:3:
include/device_proto.h:48:3: warning: field '' with variable sized type 'union (anonymous union at include/device_proto.h:48:3)' not at the end
      of a struct or class is a GNU extension [-Wgnu-variable-sized-type-not-at-end]
  union {
  ^
/usr/include/c++/v1/type_traits:2867:38: note: in instantiation of template class
      'nitrokey::proto::HIDReport<nitrokey::proto::CommandID::GET_STATUS, nitrokey::proto::EmptyPayload>' requested here
    : public integral_constant<bool, __is_pod(_Tp)> {};
                                     ^
include/device_proto.h:145:22: note: in instantiation of template class
      'std::__1::is_pod<nitrokey::proto::HIDReport<nitrokey::proto::CommandID::GET_STATUS, nitrokey::proto::EmptyPayload> >' requested here
  static_assert(std::is_pod<OutgoingPacket>::value,

....
</pre>

**Comment by szszszsz** [comment]
Hi Cornelius!

It looks like you have used too old GCC. This library makes heavy use of some c++14 features (e.g. variable templates) which are fully supported since 5.0 version. 
https://gcc.gnu.org/projects/cxx-status.html#cxx14
Could you paste your GCC version here and/or check on newer version to confirm?

**Comment by cornelinux** [comment]
indeed it is the default in 14.04:

gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.1)

**Comment by szszszsz** [comment]
This is probably the cause. Clang tries to compile library using available GCC headers in old version which in turn cause the error. I have installed GCC 5.3 and haven't seen this on my Ubuntu 15.04. Please reopen if GCC upgrade would not help you.
