### ISSUE TITLE
Python wrapper for OTP and PINs

### ISSUE THREAD

**Issue by jans23** [Nitrokey/libnitrokey#12]
Maybe use [CFFI](https://pypi.python.org/pypi/cffi). https://gist.github.com/tonyseek/7821993

**Comment by szszszsz** [comment]
What about http://www.boost.org/doc/libs/1_61_0/libs/python/doc/html/index.html ?
I will compare these and write results here.

**Comment by jans23** [comment]
[Cython](http://docs.cython.org/src/userguide/wrapping_CPlusPlus.html)

**Comment by szszszsz** [comment]
A complete list of integrating frameworks with python: [link](https://wiki.python.org/moin/IntegratingPythonWithOtherLanguages)

**Comment by szszszsz** [comment]
Done using CFFI with latest commit on master. Please check the Readme.
Later on a Pybind11 framework could be put to use.
