### ISSUE TITLE
USB serial number vs. Nitrokey serial number

### ISSUE THREAD

**Issue by robinkrahl** [Nitrokey/libnitrokey#171]
The serial number in the USB descriptor has 12 bytes, whereas the Nitrokey serial number exposed via the API has four bytes.  Based on the output for my test device, I assumed that the Nitrokey serial number is just the least significant part of the USB serial number, with the remaining bytes being zero.  But now I discovered that this is not true for my production device.

So my question is: How do the two serial numbers correlate?

Here is some demo output.  I replaced the actual values, but I think the point is clear:

Test device:

```
$ nitrocli status | grep serial
  serial number:     0x00005678
$ gpg --card-status | grep Serial
Serial number ....: 00005678
$ lsusb -d 20a0:4108 -v | grep iSerial
  iSerial                 3 000000000000000000005678
```

Production device:
```
$ nitrocli status | grep serial
  serial number:     0x00001234
$ gpg --card-status | grep Serial
Serial number ....: 00001234
$ lsusb -d 20a0:4108 -v | grep iSerial
  iSerial                 3 000012340000000000000000
```

**Comment by robinkrahl** [comment]
I just noticed that my production device has the firmware version 0.8 while my test device has 0.10.  Could this be the reason for the difference?

**Comment by szszszsz** [comment]
Hi!

The USB serial number is composed from the smart card's one - query is sent just at the beginning of the boot. Indeed in the older firmware it was written in the wrong place, which was corrected in the later firmware release (by moving to the end of the `iSerial` string).

**Comment by robinkrahl** [comment]
Thanks for the explanation!  So I could use the last four bytes and only if they are all zero use the first four bytes instead, right?

**Comment by szszszsz** [comment]
Yes, that algorithm should work with the current firmwares, if you only care about the smart card serial (with the skipping of the leading zeroes in the latter case). We do not plan changing it in the future, however in general I think these should be treated as-is for the device identification. Perhaps your use case with parsing is not critical, but wanted to signalize this anyway.

You are welcome!

**Comment by robinkrahl** [comment]
I agree that it would be better if we would not have to change them, but that would mean that the device would have two different serial numbers – one in the USB descriptor, and one in the `GET_STATUS` command and in `gpg --card-status`.  So I think for now it is better to only use one ID.
