### ISSUE TITLE
Debian package failing to build

### ISSUE THREAD

**Issue by twrightsman** [Nitrokey/libnitrokey#188]
Not sure if this is the right place to raise the issue, but the [Debian package](https://tracker.debian.org/pkg/libnitrokey) is failing to build and scheduled to be removed today. Could it also be upgraded to 3.6? @kitterma

**Comment by Prezu** [comment]
It's not. You should've submitted to bugs.debian.org. Anyway, I fixed it in Debian, so this issue can be resolved. @szszszsz Would you resolve this one?

**Comment by twrightsman** [comment]
It was at the time I posted this. It looks like that has been resolved, which is great. And yes, it would have been a better fit in the Debian bug tracker.
