### ISSUE TITLE
Cannot detect Nitrokey FIDO2 with provided test script

### ISSUE THREAD

**Issue by herrfeder** [Nitrokey/libnitrokey#192]
I'm not able to trigger any interaction with the Nitrokey FIDO2 Stick using libnitrokey and the python3 test script from the README.md :

```bash
$:~/temp/libnitrokey$ python3 python3_test.py -v
Imported 88 declarations
Trying ./build/libnitrokey.so
Found: /home/sysgen/temp/libnitrokey/build/libnitrokey.so
Could not connect to Nitrokey device!
```

Although using Chromium utilities and passwordless.dev the interaction works fine:

![](https://imgur.com/l7WNUtB.jpg)

And therefore I'm assuming udev rules and other USB issues cannot be blamed.

I'm heading to use multiple FIDO2 for enrollment with privacyIDEA and therefore I need an working interaction with libnitrokey.so.

Thank you.

**Comment by szszszsz** [comment]
Hi!

libnitrokey does not support Nitrokey FIDO2 at the moment. You can interact with it using `pynitrokey`:
- https://github.com/Nitrokey/pynitrokey#pynitrokey

**Comment by herrfeder** [comment]
Wow that was fast. Thank you. I will give pynitrokey a try and will check on Browser-based U2F. I was assuming the Support for FIDO2 as it isn't stated otherwise, the included udev rules and in the repo the line

```python
device_connected = libnitrokey.NK_login_auto()  # connect to any Nitrokey Stick
```

told me that the FIDO2 is meant, too. Thank you again.
