### ISSUE TITLE
NK_list_devices() hangs with plugged in Nitrokey FIDO2 device

### ISSUE THREAD

**Issue by daringer** [Nitrokey/libnitrokey#193]
**Bug report:** The `NK_list_devices()` C-API call, while a Nitrokey FIDO2 device is plugged in, will never return and load one cpu.

**How to reproduce:**
* make sure you have a Nitrokey FIDO2 and a Nitrokey Pro (2) / Storage (2) plugged in
* `libnitrokey` and its headers must be installed
* create a file (and save it as `nk.cc`) with the following content: 
```C
#include <libnitrokey/NK_C_API.h>
#include <iostream>

using namespace std;

int main() {
	struct NK_device_info* x = NK_list_devices();
	cout << x->model << endl;
	cout << x->path << endl;
	cout << x->serial_number << endl;
}
```
* compile it using: `g++ nk.cc -o nk -lnitrokey -I/usr/include`
* run it: `./nk`

**Observed behavior:** The executable will hang inside the `NK_list_devices()` call

**Expected behavior:** The executable should return immediately, while ignoring any other devices 

**Environment:**
* Arch Linux (Kernel 5.9.12-arch1-1, AMD64)
* libnitrokey version 3.6 (package release 1)
* Nitrokey FIDO2 & Nitrokey Pro 2

**Comment by robin-nitrokey** [comment]
I have the same issue with libnitrokey 3.6 on Debian with kernel 5.10.0-0.bpo.4-amd64.
