### ISSUE TITLE
Missing release for nk3 updates

### ISSUE THREAD

**Issue by freswa** [Nitrokey/libnitrokey#212]
nk3 update requires udev rules for the bootloader to be recognized. The latest release 3.6 doesn't include them, though the rules in master work fine. Is the any chance we can have a 3.7 release to have the correct udev rules packaged upstream?

Thanks :)

**Comment by szszszsz** [comment]
Hi!
Yes! I plan to run this next week.

**Comment by dvzrv** [comment]
any news on this? :)

**Comment by szszszsz** [comment]
On track! Got a bit delayed by holiday season, but will be taken soon.

**Comment by szszszsz** [comment]
Released today as v3.7:
- https://github.com/Nitrokey/libnitrokey/releases/tag/v3.7

Closing as done.
