### ISSUE TITLE
3c nfc on freebsd 13.2 x64

### ISSUE THREAD

**Issue by UlrichVonRekkenin** [Nitrokey/libnitrokey#224]
I got a new `Nitrokey 3C NFC` device.
- no one `pytest`
- no one `catch` tests (exclude version number)
do not pass.

Branch `master`.

Is it a correct repo for this device?

NB
41-nitrokey.rules copied to /etc/udev/rules.d
service devd restart
reboot

**Comment by robin-nitrokey** [comment]
Sorry, I somehow missed the notification for this issue.  libnitrokey only supports older Nitrokey devices like the Nitrokey Pro and Storage.  Nitrokey 3 can be used with https://github.com/Nitrokey/pynitrokey or https://github.com/Nitrokey/nitrokey-app2.
