### ISSUE TITLE
Pass binary data (OTP secrets) coded as hex values

### ISSUE THREAD

**Issue by cornelinux** [Nitrokey/libnitrokey#31]
I am integrating libnitroky in the command line client of privacyIDEA to initialize the (H)OTP slots.
I am creating a "random" OTP seed to initilize the slot with NK_write_hotp_slot.

I think I stumbled upon a small problem. Once my random bytestring contain \x00. Right at the first position. So I guess the C++ implementation interpreted this as an empty seed. And in fact the OTP values did not match.

Maybe we should allow to pass a hexlified string as seed/otp_key

**Comment by szszszsz** [comment]
Indeed, '0' is not currently supported in any field. It is used as a terminator like with a regular string.
I agree using hexified input is the solution.
