### ISSUE TITLE
No library function for getting device's serial number

### ISSUE THREAD

**Issue by cornelinux** [Nitrokey/libnitrokey#33]
When initializing the nitrokey, I would like to retrieve the serial number of the key.
What is the best way, to retrieve this? NK_status?
How would I have to interpret the returned structure?

**Comment by szszszsz** [comment]
Currently the only way is to use `NK_status()` function and parsing its string output. However implementation of dedicated function should not be an problem.

**Comment by cornelinux** [comment]
I managed to adapt my python code to transform the return value of status() to a dict. Works fine for me, for now. Thx!
