### ISSUE TITLE
"no-gnu-variable-sized-type-not-at-end"  command not recognized (debian, g++ 4.9.2)

### ISSUE THREAD

**Issue by Dowwie** [Nitrokey/libnitrokey#39]
I'm using Debian 8 with gnome, g++ 4.9.2.  I had no luck with getting the nitrokey-app widget to appear but since that's not a requirement for my work I decided to skip that step and instead focus on the python bindings.  

Unfortunately, I haven't been able to successfully build the libnitrokey project using "make" or "make CXX=g++".  The first except, which I resolved,  was a lib dependency that wasn't mentioned in the docs, namely libhidapi-dev.  The next exception I haven't been able to resolve.  

The more verbose exception, raised with "make CXX=G++" is as follows:
```bash
g++ -M log.cc -o build/log.d -Iinclude/ -std=c++14 -fPIC -Wno-gnu-variable-sized-type-not-at-end
g++ -M NK_C_API.cc -o build/NK_C_API.d -Iinclude/ -std=c++14 -fPIC -Wno-gnu-variable-sized-type-not-at-end
g++ -M device.cc -o build/device.d -Iinclude/ -std=c++14 -fPIC -Wno-gnu-variable-sized-type-not-at-end
g++ -M misc.cc -o build/misc.d -Iinclude/ -std=c++14 -fPIC -Wno-gnu-variable-sized-type-not-at-end
g++ -M command_id.cc -o build/command_id.d -Iinclude/ -std=c++14 -fPIC -Wno-gnu-variable-sized-type-not-at-end
g++ -M NitrokeyManager.cc -o build/NitrokeyManager.d -Iinclude/ -std=c++14 -fPIC -Wno-gnu-variable-sized-type-not-at-end
g++ -c log.cc -o build/log.o -Iinclude/ -std=c++14 -fPIC -Wno-gnu-variable-sized-type-not-at-end
log.cc: In member function ‘virtual void nitrokey::log::StdlogHandler::print(const string&, nitrokey::log::Loglevel)’:
log.cc:39:16: error: ‘put_time’ is not a member of ‘std’
             << std::put_time(&tm, "%c %Z") << "]\t" << str << std::endl;
                ^
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-gnu-variable-sized-type-not-at-end"
Makefile:28: recipe for target 'build/log.o' failed
make: *** [build/log.o] Error 1
```

**Comment by szszszsz** [comment]
Hi!
Sorry for missed dependency, I will update readme. 

The library was developed and tested on g++ with versions 5.2 up. Variable templates (a feature of c++14) is not supported by your version. Please check [table 1](https://gcc.gnu.org/projects/cxx-status.html#cxx14) or [table 2](http://en.cppreference.com/w/cpp/compiler_support) for support table.
My current g++:
```bash
$ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609
```

**Comment by Dowwie** [comment]
If you haven't personally experienced installing a newer C++ compiler in debian then you may not understand why I am not going to try to upgrade it, especially since this is the only library that I'd need the latest compiler for.  The latest Debian release upgrades to 6.1 but it's not out yet and again, upgrading just to satisfy this project would conflict with other priorities.
