### ISSUE TITLE
Fail to build branch hotp_tests on Ubuntu 14.04

### ISSUE THREAD

**Issue by cornelinux** [Nitrokey/libnitrokey#4]
I am longing to integrate the libnitrokey into my project (https://github.com/privacyidea/privacyidea) to provide a management solution for many nitrokeys.

To do so I am taking a look at the branch **hotp_tests** but I failed to build it.

I am on Ubuntu 14.04.
I figured out to install libc++-dev and add 

    CXXFLAGS = -std=c++14 -fPIC  -stdlib=libc++

in the Makefile.

But I am ending up with 

<pre>
cornelius@puckel ~/src/libnitrokey (git)-[hotp_tests] % LANG=en_US make
clang++-3.6 -c command_id.cc -o build/command_id.o -Iinclude/ -std=c++14 -fPIC  -stdlib=libc++
clang++-3.6 -c device.cc -o build/device.o -Iinclude/ -std=c++14 -fPIC  -stdlib=libc++
In file included from device.cc:6:
include/device.h:43:3: warning: declaration does not declare anything [-Wmissing-declarations]
  const;
  ^~~~~
include/device.h:45:3: warning: declaration does not declare anything [-Wmissing-declarations]
  const;
  ^~~~~
2 warnings generated.
clang++-3.6 -c log.cc -o build/log.o -Iinclude/ -std=c++14 -fPIC  -stdlib=libc++
clang++-3.6 -c misc.cc -o build/misc.o -Iinclude/ -std=c++14 -fPIC  -stdlib=libc++
misc.cc:15:40: warning: format specifies type 'unsigned int' but the argument has type 'long' [-Wformat]
    snprintf(formatbuf, 128, "%04x\t", p - pstart);
                              ~~~~     ^~~~~~~~~~
                              %04lx
1 warning generated.
clang++-3.6 -shared build/command_id.o build/device.o build/log.o build/misc.o -lhidapi-libusb -o build/libnitrokey.so
make -C unittest
make[1]: Entering directory `/home/cornelius/src/libnitrokey/unittest'
clang++-3.6 -M test.cc -o build/test.d -I../include -ICatch/single_include/ -std=c++14 -fPIC
test.cc:2:10: fatal error: 'catch.hpp' file not found
#include "catch.hpp"
         ^
1 error generated.
make[1]: *** [build/test.d] Error 1
make[1]: Leaving directory `/home/cornelius/src/libnitrokey/unittest'
make: *** [unittest] Error 2
</pre>

Are there any build instructions?

**Comment by szszszsz** [comment]
Hi Cornelius!

Libnitrokey is still a work in progress - not all features are working yet nor were tested. It is a low level API without any documentation yet. Until we prepare it, the unit tests should be helpful for you. Please think about it as experimental for now. Also, making a higher level API (much easier to use for users outside project) is planned.

Responding to question, the issue comes from not cloning Catch framework. 
Please _git clone_  submodules into your setup after initial _git clone_ by running:
> cd libnitrokey
> git submodule update --init --recursive

Let me know if that helped.

**Comment by cornelinux** [comment]
Thanks. Now I successfully built build/libnitrokey.so.
If you have anything to watchout or any need for feedback that would be valuable for you, drop me a note.

As mentioned. I am trying to start using the OTP-functions.

**Comment by szszszsz** [comment]
All kinds of feedback and help are welcomed!
Since you already want to integrate libnitrokey with other project, could you propose some functions for libnitrokey high-level API? 
I will make separate issue for that.

**Comment by szszszsz** [comment]
I have created issue #5 for high-level API. Feel free to create issues with other ideas or feedback.
