### ISSUE TITLE
Make contributions easier

### ISSUE THREAD

**Issue by Hopetech** [Nitrokey/libnitrokey#61]
The issues labels are quite difficult to understand.
For example, what does "ready" label mean? Did you already have the feature somewhere?

**Comment by szszszsz** [comment]
Hi!
Indeed this is quite confusing. I was using waffle.io to manage issues and `ready` label was one of their default. Here is the page with summary using it: https://waffle.io/Nitrokey/libnitrokey
I have changed the `ready` label to `ready to work on`. This should be clearer.
Do you have any other problematic labels?

**Comment by Hopetech** [comment]
Hello,
Thank you for that clarification. So I have a PR for #35 incoming.
Label A, B and C are also confusing.

**Comment by szszszsz** [comment]
Great!
The A,B,C labels mean issue priority, where A is the highest. I preferred them to be short since they are common. I have worked with such names earlier too.
If they look confusing they can be renamed to `priority:A` etc. - how about that?

**Comment by Hopetech** [comment]
Sounds good to me.

**Comment by szszszsz** [comment]
Done!
Closing as `invalid` since this is not a project issue (so it should not count to changelog).
