### ISSUE TITLE
cmake doesn't install any headers

### ISSUE THREAD

**Issue by ignatenkobrain** [Nitrokey/libnitrokey#70]
There is

```cmake
file(GLOB LIB_INCLUDES "include/libnitrokey/*.h")
install (FILES ${LIB_INCLUDES} DESTINATION "include")
```

in the CMakeLists.txt, but there is basically no `libnitrokey` directory, so cmake doesn't install any header files..

**Comment by ignatenkobrain** [comment]
@szszszsz thanks a lot!

I submitted review request for inclusion of libnitrokey into Fedora (https://bugzilla.redhat.com/show_bug.cgi?id=1499408) and hopefully soon I will update nitrokey-app in Fedora to the latest version.

Thanks again!

**Comment by szszszsz** [comment]
My pleasure! Feel free to let me know if there are any other issues with making packages.
And thank you for updating it!
