### ISSUE TITLE
Debian / symbols not as expected while building

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/libnitrokey#84]
Some Debian's builds reports different symbols set than expected.
(issue created for monitoring)
Details:
https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1572391.html

Copied from: https://github.com/Nitrokey/nitrokey-app/issues/308

**Comment by kitterma** [comment]
Note that this is fixed in Debian.

**Comment by kitterma** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=885242#22

**Comment by szszszsz** [comment]
Thank you. Closing then.
