### ISSUE TITLE
Please do a release ...

### ISSUE THREAD

**Issue by kitterma** [Nitrokey/libnitrokey#87]
nitrokey-app uses the libnitrokey pkg-config file to detect the presence of the library, but there's no libnitrokey release with this update.  I've patched it into the Debian package so as not to block the Debian nitrokey-app getting updated, but it would be much nicer to have it in a proper upstream release.

**Comment by szszszsz** [comment]
Hi!
It should be done within 2 days.

**Comment by szszszsz** [comment]
Here it is: [v3.2](https://github.com/Nitrokey/libnitrokey/releases/tag/v3.2)

**Comment by kitterma** [comment]
Thanks.  I've uploaded it to Debian Unstable.
