### ISSUE TITLE
Buffer over-read when calling strtoul in hex_string_to_byte (misc.cc)

### ISSUE THREAD

**Issue by robinkrahl** [Nitrokey/libnitrokey#95]
The `hex_string_to_byte` function in `misc.cc` calls `strtoul` with a non-null-terminated string, causing a buffer over-read.  The function calls `strtoul(buf, NULL, 16)` in line 56, where `buf` is a character array of size two.  Both characters are set to non-null values before the call.

This also causes failing tests if the next character stored in memory happens to be non-null.

**Comment by szszszsz** [comment]
Fixed. Closed by #96
